import SwiftUI
import AppKit

struct ClipboardManager {
    static let pasteSessionType = NSPasteboard.PasteboardType("com.Diktilo.PasteSession")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    enum ClipboardError: Error {
        case copyFailed
        case accessDenied
    }

    static func setClipboard(_ text: String, transient: Bool = false, sessionID: String? = nil) -> Bool {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        guard pasteboard.setString(text, forType: .string) else {
            return false
        }

        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            pasteboard.setString(bundleIdentifier, forType: sourceType)
        }

        if transient {
            pasteboard.setData(Data(), forType: transientType)
            pasteboard.setData(Data(), forType: autoGeneratedType)
        }

        if let sessionID, !pasteboard.setString(sessionID, forType: pasteSessionType) {
            return false
        }

        return pasteboard.string(forType: .string) == text
    }

    static func copyToClipboard(_ text: String) -> Bool {
        return setClipboard(text, transient: false)
    }

    /// UserDefaults key for the "auto-copy every completed transcription"
    /// preference. Default (true) is registered in `AppDefaults`.
    static let autoCopyEnabledKey = "AutoCopyTranscriptionEnabled"

    /// Whether every completed transcription is automatically placed on the
    /// system clipboard — the use-case is landing transcripts in a clipboard
    /// manager's history (e.g. Alfred). Defaults to true.
    static var isAutoCopyEnabled: Bool {
        UserDefaults.standard.bool(forKey: autoCopyEnabledKey)
    }

    /// Copies a completed transcription to the clipboard when auto-copy is
    /// enabled. No-ops on empty text so it never wipes the user's clipboard,
    /// and copies non-transiently so clipboard managers record the entry.
    @discardableResult
    static func autoCopyTranscription(_ text: String) -> Bool {
        guard isAutoCopyEnabled,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return false
        }
        return copyToClipboard(text)
    }

    static func getClipboardContent() -> String? {
        return NSPasteboard.general.string(forType: .string)
    }
}

struct ClipboardMessageModifier: ViewModifier {
    @Binding var message: String
    
    func body(content: Content) -> some View {
        content
            .overlay(
                Group {
                    if !message.isEmpty {
                        Text(message)
                            .font(.caption)
                            .foregroundColor(AppTheme.Status.positive)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 4)
                            .background(AppTheme.Status.positive.opacity(0.10))
                            .cornerRadius(4)
                            .transition(.opacity)
                            .animation(.easeInOut, value: message)
                    }
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topTrailing)
                .padding()
            )
    }
}

extension View {
    func clipboardMessage(_ message: Binding<String>) -> some View {
        self.modifier(ClipboardMessageModifier(message: message))
    }
}
